"""Generate reports/VIVA_QA.md from reports/templates/VIVA_QA.template.md.

Numbers are {{key}} placeholders filled from results/ by src/report_facts.py.
Run: python scripts/make_viva_qa.py
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.report_facts import render  # noqa: E402

TEMPLATE = ROOT / "reports" / "templates" / "VIVA_QA.template.md"
OUTPUT = ROOT / "reports" / "VIVA_QA.md"
HEADER = (
    "<!-- Generated by scripts/make_viva_qa.py from "
    "reports/templates/VIVA_QA.template.md. Do not edit by hand. -->\n\n"
)


def build():
    OUTPUT.write_text(HEADER + render(TEMPLATE.read_text(encoding="utf-8")), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    build()
