"""Render the final validation record from captured results/ evidence."""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.report_facts import render_validation  # noqa: E402

TEMPLATE = ROOT / "reports/templates/FINAL_VALIDATION.template.md"
OUTPUT = ROOT / "docs/FINAL_VALIDATION.md"
HEADER = "<!-- Generated by scripts/make_final_validation.py; edit the template, not this file. -->\n\n"


def document():
    return HEADER + render_validation(TEMPLATE.read_text(encoding="utf-8"))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = document()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("FAIL final validation: generated document is stale")
        print("PASS final validation: generated document is current")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")
        print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
